### PR TITLE
Rewrite to always use external call. Added tests. Cleaned up.

### PR DESCRIPTION
**Pull request by goloroden**
I saw your module while searching StackOverflow. I liked it, but I was not convinced by the two approaches, and I did not like the usage of temporary files.

Hence, I've rewritten it. Now it is always reliable, as it always calls out to the external `node` process.

Additionally, I've made some improvements:
- It directly captures output, hence it does not need to write files.
- Code is _way_ shorter.
- I added a few tests.
- I added a `Gruntfile.js`.
- I added code analysis using ESLint.
- I rewrote the documentation to be more complete.

I hope that you like it, and that you aren't mad at me because I changed so many things :-)

### CODE REVIEW

**Comment by alexpods** [comment]
@goloroden Thanks for contribution! Yeah,  I think your pull request is deserved to be merge. But I have several suggestions for improvements:
1. `execSync` method was added in `node v0.11.12`. I think library should support old node versions too (especially  `v0.10.x`). So would be great to add check of `execSync` method existence 
2. Actually we must make external call only once. It absolutely redundant to do it second time. So we can cache result of `execSync` call to some variable and return it on repeated calls. We can provide option, for someone really want to make `execSync` call again.
3. Now `node` and `io.js` could not exist  "side by side", but they can be executed from the different places. So I think we must use `process.execPath` to get help message.
4. We don't need `utf8` encoding, `ascii` is enough. It'll be a little faster.

So I think result solution must be:

``` js
var cp = require('child_process');
var _isIojs = null;

module.exports = function isIojs(force) {
    if (!force && _isIojs !== null) {
        return _isIojs;
    }
    if (!cp.execSync) {
        return _isIojs = false;
    }
    return _isIojs = /iojs\.org/.test(cp.execSync(process.execPath + ' -h', { encoding: 'ascii' }));
};
```

Tell me what do you think. When we make a decision about all of this, I'll merge your PR. 

**PS**. Extra thanks for tests:) And add yourself to the license, after all that's all is your code.

**Comment by goloroden** [comment]
Hey man, thanks for your feedback, and I'm glad you like it :-)

Ad 1: Yep, you're right.

Ad 2: Here, you're right, too. ~~Actually, the only reason why I did not do this is because this would have meant to introduce some kind of a `forget` method for the tests, so that you are able to run each test individually from each other.~~ This should be quite an easy one thanks to the usage of `proxyquire`.

Besides, I have been wondering how many times you'll run this code in production anyway (if you only do it once, e.g. at startup, it doesn't matter whether it's cached or not).

Ad 3: Meanwhile I've found the [detect-engine](https://github.com/silverwind/detect-engine) module, and they do exactly this.

Ad 4: Generally speaking, I'd say this is micro-optimizing ;-). But yeah, you're right.

Would it be okay for you if you take my PR just as the foundation to adjust the remaining things for yourself? To be honest, I'm not going to have the time within the next days, but if you want to proceed, feel free to do so :-)

**Comment by alexpods** [comment]
@goloroden Ok, then. I'll merge your PR, make changes, bump version to the 1.0.0 and add you to the license:)

**Comment by goloroden** [comment]
Wow, thanks :-)

**Pull request merged**
